### ISSUE TITLE
need some help please. 

### ISSUE THREAD

**Issue by putilatex** [knaggsy2000/stormforce-mq#1]
Hi Danny,
I have got myself a Boltek LD-250 and your stornforce-mq software.
I have been busy upgrading your stormforce-mq to use python 3. I have mainly got it going.
I have 3 connections to rabbitmq, 2 from smq_server.py and 1 from smq_client.py but nothing else.
I have manually created 3 queue's that show their payloads correctly but no data is going into the smq_client.py.
I have a few questions about this, so some help from you would be really great.
many thanks in advance.

Cheers Sean
P.S nice software ! :-)

**Comment by knaggsy2000** [comment]
Sean, sorry again for the delay in replying.  I'm in the process of updating some the repos hosted on here to Python v3.X as I now know that Python v2.X is considered obsolete and no longer updated.  It has been quite sometime since someone has mentioned about StormForce in many years and annoyingly my LD-250 has been misplaced :/  good job I made a emulator for it (at a cost of requiring another serial port and a crossover cable) but that code will need updating first.

I haven't even looked at the code for it since the last public commit.  But I'm sure I can help you with any questions you have.

**Comment by putilatex** [comment]
Hi Danny,
Good to hear from you :-)
Perhaps we can help each other here. 
I must say I am not a coder, I just like to tinker. I think I have made a good job of upgrading the software to python 3 but there are things that are not working as desired.
firstly a couple of points about missing files in the repo
 there was not ttf and png folders so I had to burgle these from the old XR version :-)
secondly under python 3 I am having problems with the squelch algorithm I can't seem to find a way to get this to work without complaints. I have tried different things found on the net but nothing that stops the complaints in terminal.
thirdly in class SentenceDevice() in the smq_shared.py I got this working but it does produce a complaint when multiple strikes have been detected, my guess is it causes a buffer overflow (only a guess :-)) and will crash the class only a restart solves the problem.
I think Rabbit-mq has moved on a bit too.
When I ran smq_server.py at first there was no connection to rabbit-mq and lots of complaints in the terminal but after adding this to smq_shared.py 

def onMessageReceived(self, basic_deliver, properties, body):
	self.log.debug("Starting...")
	self.onMessageReceived = message_callback

I do get two connections for the server and the exchange StormForce.MQ.Server is created but nothing else.
If I then run sqm_client.py I then get a third connection but nothing else.
I take it that the events.# queue should automatically be created and some channels for consumption ??
Anyway that's my stand at the moment.
I may be able to help you with your missing hardware, I do have an extra antenna which I would gladly give to you.
It's the first version ANT-1 just a black box without the pole fitting.
also If you would like to take a look at my files I can zip these up and send to you.

P.S take a look here, it's going to be part of my template:
https://skynetweather.com/html/weather34/index.php

**Comment by knaggsy2000** [comment]
I'm sorry that I haven't been very communicative - personal reasons.

I haven't had any feedback that people are still looking at this project for support in quite a few years.  As this project (like others on my repos) have aged a little since Python has moved on from v2.X to v3.X.  So haven't felt a need to update them.
